services:
  server:
    container_name: invest_server
    ports:
      - "2000:2000"
    restart: unless-stopped

  client:
    container_name: invest_client
    ports:
      - "1000:80"
    restart: unless-stopped
