import express from 'express';
import cors from 'cors';
import { config } from './config.js';
import { getLabDetail, searchInvestigation } from './services/emrService.js';
import {
  getReportPdfUrl,
  getReportRecord,
  getReportSummaryPdfUrl,
  getSchedulerStatus,
  listReportDates,
  loadReportIndex,
  runBackfillForDate,
  runDischargeCheck,
  searchReports,
  startDischargeScheduler,
} from './services/dischargeReportService.js';
import { pdfExists, reportObjectKey, reportSummaryObjectKey } from './services/storageService.js';
import { getWatiSettings, updateWatiSettings } from './services/watiSettingsService.js';
import { sendInvestigationReportWhatsApp } from './services/watiService.js';

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const candidatePaths = [
  path.join(__dirname, '../../client/dist'),
  path.join(__dirname, '../client/dist'),
  path.join(__dirname, '../dist'),
  path.join(__dirname, '../../dist'),
  path.join(__dirname, './dist'),
];

const clientDistPath = candidatePaths.find((p) => fs.existsSync(path.join(p, 'index.html'))) || candidatePaths[0];

export function createApp() {
  const app = express();

  app.use(cors());
  app.use(express.json());

  // Serve static frontend files (React dist)
  app.use(express.static(clientDistPath));

  app.get('/api/health', (_req, res) => {
    res.json({ ok: true });
  });

  app.post('/api/login', (req, res) => {
    const { username, password } = req.body || {};

    if (!username || !password) {
      return res.status(400).json({ ok: false, error: 'Username and password are required' });
    }

    const isValid = username === config.auth.username && password === config.auth.password;

    if (!isValid) {
      return res.status(401).json({ ok: false, error: 'Invalid username or password' });
    }

    res.json({ ok: true, username });
  });

  app.get('/api/config/hospital', (_req, res) => {
    res.json(config.hospital);
  });

  app.post('/api/search', async (req, res) => {
  const { regNo, fromDate, toDate } = req.body || {};

  if (!regNo?.trim() || !fromDate || !toDate) {
    return res.status(400).json({ ok: false, error: 'regNo, fromDate, and toDate are required' });
  }

  try {
    const result = await searchInvestigation(regNo.trim(), fromDate, toDate);
    if (!result.ok) {
      return res.status(500).json(result);
    }
    res.json(result);
  } catch (error) {
    res.status(500).json({ ok: false, error: error.message });
  }
});

app.get('/api/detail/:orderid', async (req, res) => {
  const orderid = String(req.params.orderid || '').trim();

  if (!orderid || !/^\d+$/.test(orderid)) {
    return res.status(400).json({ ok: false, error: 'Missing or invalid orderid' });
  }

  try {
    const result = await getLabDetail(orderid);
    if (!result.ok) {
      return res.status(500).json(result);
    }
    res.json(result);
  } catch (error) {
    res.status(500).json({ ok: false, error: error.message });
  }
});

  /**
   * Discharge report automation (read-only browsing endpoints).
   *
   * PDFs live in MinIO at <YYYY-MM-DD>/<IP_NO>.pdf, generated by the hourly
   * scheduler in dischargeReportService.js; metadata lives in Mongo. Date and IP
   * number are both matched against a strict whitelist before being used to build
   * an object key or Mongo filter from request input.
   */
  const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
  const IP_RE = /^[A-Za-z0-9]{1,20}$/;

  app.get('/api/reports/status', (_req, res) => {
    res.json({ ok: true, ...getSchedulerStatus() });
  });

  app.get('/api/reports/dates', async (_req, res) => {
    try {
      res.json({ ok: true, dates: await listReportDates() });
    } catch (error) {
      res.status(503).json({ ok: false, error: `Reports store unavailable: ${error.message}` });
    }
  });

  // Must come before /api/reports/:date — otherwise Express would match "search"
  // as the :date param and reject it as an invalid date.
  app.get('/api/reports/search', async (req, res) => {
    try {
      const patients = await searchReports(req.query);
      res.json({ ok: true, patients });
    } catch (error) {
      res.status(503).json({ ok: false, error: `Reports store unavailable: ${error.message}` });
    }
  });

  app.get('/api/reports/:date', async (req, res) => {
    const { date } = req.params;
    if (!DATE_RE.test(date)) {
      return res.status(400).json({ ok: false, error: 'Invalid date format, expected YYYY-MM-DD' });
    }
    try {
      res.json({ ok: true, date, patients: await loadReportIndex(date) });
    } catch (error) {
      res.status(503).json({ ok: false, error: `Reports store unavailable: ${error.message}` });
    }
  });

  /**
   * Redirects to a short-lived MinIO presigned URL rather than proxying the PDF
   * bytes through this server — the browser downloads directly from MinIO, and a
   * plain <a href> / target="_blank" still works transparently across the redirect.
   */
  app.get('/api/reports/:date/:ip/pdf', async (req, res) => {
    const { date, ip } = req.params;
    if (!DATE_RE.test(date) || !IP_RE.test(ip)) {
      return res.status(400).json({ ok: false, error: 'Invalid date or IP number' });
    }

    try {
      if (!(await pdfExists(reportObjectKey(date, ip)))) {
        return res.status(404).json({ ok: false, error: 'Report not found' });
      }
      res.redirect(await getReportPdfUrl(date, ip));
    } catch (error) {
      res.status(503).json({ ok: false, error: `Reports store unavailable: ${error.message}` });
    }
  });

  /** The EMR's own discharge summary document — separate from the lab chart above. */
  app.get('/api/reports/:date/:ip/summary-pdf', async (req, res) => {
    const { date, ip } = req.params;
    if (!DATE_RE.test(date) || !IP_RE.test(ip)) {
      return res.status(400).json({ ok: false, error: 'Invalid date or IP number' });
    }

    try {
      if (!(await pdfExists(reportSummaryObjectKey(date, ip)))) {
        return res.status(404).json({ ok: false, error: 'Discharge summary not found' });
      }
      res.redirect(await getReportSummaryPdfUrl(date, ip));
    } catch (error) {
      res.status(503).json({ ok: false, error: `Reports store unavailable: ${error.message}` });
    }
  });

  /** Manual trigger so you don't have to wait up to an hour to see it work. */
  app.post('/api/reports/run-now', async (_req, res) => {
    try {
      const summary = await runDischargeCheck();
      res.json({ ok: true, summary });
    } catch (error) {
      res.status(500).json({ ok: false, error: error.message });
    }
  });

  /**
   * Backfill a past date. The live scheduler only ever checks "today", so a
   * date that's already gone by is otherwise never revisited — this runs the
   * identical per-patient logic against a caller-supplied date instead. Can
   * take a while for a busy day (one EMR round-trip per missing document), so
   * this is meant to be fired and then watched via /api/reports/status.
   */
  app.post('/api/reports/backfill/:date', async (req, res) => {
    const { date } = req.params;
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
      return res.status(400).json({ ok: false, error: 'Invalid date format, expected YYYY-MM-DD' });
    }
    try {
      const summary = await runBackfillForDate(date);
      res.json({ ok: true, summary });
    } catch (error) {
      res.status(500).json({ ok: false, error: error.message });
    }
  });

  /**
   * WATI live-mode settings — see watiSettingsService.js. `liveEnabled: false`
   * (the default) routes manual sends to `fixedNumber` instead of real patient
   * numbers, and disables the automation's auto-send entirely.
   */
  app.get('/api/wati/settings', async (_req, res) => {
    try {
      res.json({ ok: true, settings: await getWatiSettings() });
    } catch (error) {
      res.status(503).json({ ok: false, error: `Settings store unavailable: ${error.message}` });
    }
  });

  app.post('/api/wati/settings', async (req, res) => {
    try {
      res.json({ ok: true, settings: await updateWatiSettings(req.body || {}) });
    } catch (error) {
      res.status(500).json({ ok: false, error: error.message });
    }
  });

  /**
   * Manual "Send WhatsApp" trigger for a patient's lab report (never the
   * discharge summary). Target number depends on WATI live mode: the
   * patient's own mobile on file when live, otherwise the configured fixed
   * test number — same rule the automation's auto-send follows.
   */
  app.post('/api/reports/:date/:ip/send-whatsapp', async (req, res) => {
    const { date, ip } = req.params;
    if (!DATE_RE.test(date) || !IP_RE.test(ip)) {
      return res.status(400).json({ ok: false, error: 'Invalid date or IP number' });
    }
    try {
      if (!(await pdfExists(reportObjectKey(date, ip)))) {
        return res.status(404).json({ ok: false, error: 'Lab report not found' });
      }

      const [record, settings] = await Promise.all([getReportRecord(date, ip), getWatiSettings()]);
      const toNumber = settings.liveEnabled ? record?.mobile : settings.fixedNumber;
      if (!toNumber) {
        return res.status(400).json({
          ok: false,
          error: settings.liveEnabled
            ? 'No mobile number on file for this patient'
            : 'No fixed test number configured — set one in WATI Settings first',
        });
      }

      const pdfUrl = await getReportPdfUrl(date, ip);
      const result = await sendInvestigationReportWhatsApp({
        toNumber,
        name: record?.name || ip,
        note: `Investigation report for ${record?.name || ip} (${ip})`,
        pdfUrl,
      });
      res.json({ ok: true, sentTo: toNumber, result });
    } catch (error) {
      res.status(500).json({ ok: false, error: error.message });
    }
  });

  // Fallback for Single Page Application (SPA) routing
  app.get('*', (req, res, next) => {
    if (req.path.startsWith('/api')) return next();
    res.sendFile(path.join(clientDistPath, 'index.html'));
  });

  return app;
}

const app = createApp();

app.listen(config.port, () => {
  console.log(`Server running on http://localhost:${config.port}`);
  console.log(`Serving static UI from: ${clientDistPath} (exists: ${fs.existsSync(clientDistPath)})`);
  console.log('Server restarted to load updated .env credentials!');
});

startDischargeScheduler();
